name: Water Reminder Bot

on:
  schedule:
    - cron: '0 1 * * 1-5'  # 月～金 10:00 (JST)
    - cron: '0 2 * * 1-5'  # 月～金 11:00 (JST)
    - cron: '0 5 * * 1-5'  # 月～金 14:00 (JST)
    - cron: '0 6 * * 1-5'  # 月～金 15:00 (JST)
    - cron: '0 7 * * 1-5'  # 月～金 16:00 (JST)
    - cron: '0 8 * * 1-5'  # 月～金 17:00 (JST)
  workflow_dispatch:

jobs:
  remind-water:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: 必要なライブラリをインストール
        run: pip install requests
      - name: 水飲めメッセージを送信
        env:
          LINE_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_TO: ${{ secrets.LINE_USER_ID }}
        run: python send_water_notify.py
